src/app/_components/answer.tsx, src/app/_components/question.tsx
이제 질문자가 익명이 아니라면 질문자의 테그를 누르면 질문자의 질문함으로 연결됩니다
=> Feat: 질문자의 테그를 질문자의 질문함에 링크

src/app/_dto/delete-answer/delete-answer.dto.ts, src/app/api/db/delete-answer/route.ts
* Feat: 답변 삭제 API 추가: 답변자가 답변을 삭제할 수 있는 API 추가
=> Feat: 답변 삭제 API 추가

src/app/page.tsx
와 이제 무지성 엔터키 연타 해야지!!!!!
( Fix https://github.com/Squarecat-meow/neo-quesdon/issues/25 )
=> Fix: Login Form에 바로 enter쳤을때의 required 에러 수정

src/app/api/web/fetch-name-with-emoji/route.ts, src/app/api/web/misskey-login/route.ts, src/app/page.tsx, src/utils/detectInstance/detectInstance.ts
무엇이든 자르는 장미칼!!! 장미의 아름다움과 그 안에 숨어있는 가시처럼, 아름다운 디자인과 무엇이든 잘라버리는 절삭력에 감탄하십시오!!!
- 미스키 12.27.0 이하 버전, 또는 CORS헤더가 없는 서버 로그인 지원
=> 🐛 미스키 12.27.0 이하 버전 지원

src/app/api/db/create-question/route.ts
Resolves #40 
이게 이렇게 오래걸릴게 아닌데 집중력 무엇........
=> Feat: 알림 노트에 질문자 정보 추가

.dockerignore, Dockerfile, next.config.ts, package.json
standalone 모드 빌드 딱히 별 도움이 안 되는것 같아서
=> docker 빌드 설정 변경

src/app/_dto/web/login/login.dto.ts, src/app/api/web/refresh-token/route.ts, src/app/page.tsx
* host에 hostname이 아닌 무언가가 오면 백앤드에서 뱉어낼 수 있도록
* 로그인 실패시 에러메시지 표시 개선
=> 로그인시 예외처리 개선

src/app/page.tsx
* https://github.com/serafuku/neo-quesdon/issues/49
* 생각해보니 로그인된 상태면 수동으로 로그인 버튼을 누르게 할 필요도 없을것 같아서 자동 리디렉션으로 동작을 변경
=> 로그인 상태면 자동으로 main 페이지 가도록

prisma/migrations/20241203113858_fix_index/migration.sql, prisma/schema.prisma, src/app/api/_service/queue/queueService.ts, src/app/api/_service/queue/workers/RefreshFollowService.ts, src/app/api/web/refresh-token/route.ts, src/app/mastodon-callback/action.ts
=> Mastodon follow

src/app/_components/answer.tsx, src/app/main/user/[handle]/_profile.tsx
빨대의 구멍은 한 개일까요 두 개일까요 무한개일까요?
#65 이슈 fix
=> 익명 질문 안 받기 활성화시 미트볼 버튼 가려지는 버그 수정

src/app/_components/collapseMenu.tsx, src/app/main/settings/_table.tsx, src/app/main/settings/page.tsx
재사용 가능한 CollapseMenu 컴포넌트 작성
- props에는 id, text 두 개가 들어가고 이 두 개는 필수임
- id: 구분용으로 내부 Checkbox에 달아놓은 String. 별 다른 용도는 없음
- text: 메뉴 최상단에 보이는 String.
- `<CollapseMenu>`와 `</CollapseMenu>`안에 넣고 싶은 컴포넌트를 넣어서 사용
=> 💄 <CollapseMenu> 컴포넌트 작성

src/app/main/settings/page.tsx
=> 💄 설정 페이지 스타일 수정

src/app/api/_service/login/logout-all-service.ts, src/app/api/user/logout-all/route.ts, src/app/main/settings/page.tsx
- https://github.com/serafuku/neo-quesdon/issues/48
=> 모든 기기에서 로그아웃

src/app/main/user/[handle]/_profile.tsx
다크모드에서 '작성자 공개 질문만 받아요!'  말풍선의 텍스트 색상의 가독성이 떨어지는 문제 수정
=> fix: 말풍선 텍스트 색상 수정

src/app/_dto/account-clean/account-clean.dto.ts, src/app/api/_service/queue/queueService.ts, src/app/api/_service/queue/workers/AccountClean.ts, src/app/api/user/account-clean/route.ts, src/app/main/settings/page.tsx
므아 한번 도구들 만들어 놓으니까 뚝딱뚝딱 만드네 ㅋㅋㅋㅋㅋ
=> feat: 계정 청소기능 구현

prisma/migrations/20241205030826_sync_block/migration.sql, prisma/schema.prisma, src/app/api/_misskey-entities/blocking.ts, src/app/api/_service/blocking/blocking-service.ts, src/app/api/_service/queue/queueService.ts, src/app/api/_service/queue/workers/AccountClean.ts, src/app/api/_service/queue/workers/ImportBlock.ts, src/app/api/user/blocking/import/route.ts, src/app/main/settings/page.tsx
=> Import block

src/app/main/settings/_table.tsx
=> 💄 차단목록 핸들 길어지면 잘리는 문제 수정

src/app/main/settings/page.tsx
=> 💄 설정 확인 버튼 동작 수정

src/app/main/user/[handle]/page.tsx, src/app/sitemap.ts
=> ✨ openGraph 대응

src/app/main/_header.tsx, src/app/main/_questionEvent.ts, src/app/main/questions/page.tsx
=> ✨ 질문 CustomEvent 작성

server.ts, src/app/_dto/websocket-event/websocket-event.dto.ts, src/app/api/_service/answer/answer-service.ts, src/app/api/_service/websocket/websocket-service.ts, src/app/main/_header.tsx, src/app/main/questions/action.ts
- 답변이 새로 생기거나 삭제될때 웹소켓 스트림으로 보내주도록 구현
=> Feat: 답변 생성 & 삭제시 웹소켓 이벤트

src/app/_components/question.tsx
- 질문에 대한 답변을 작성하다가 새로고침이나 페이지 이동을 한 경우 입력하던 내용이 날아가지 않도록 자동으로 저장 & 복원
=> 답변 자동 임시저장 기능

src/app/main/_events.ts, src/app/main/_header.tsx, src/app/main/layout.tsx, src/app/main/page.tsx, src/app/main/questions/page.tsx
- 글로벌 타임라인 answers 를 context로 기억, 속도 향상
=> Feat: 페이지 이동해도 글탐 기억하도록

src/app/_components/webSocketState.tsx, src/app/main/_events.ts, src/app/main/_header.tsx, src/app/main/layout.tsx
예가체프 G4 녱뇽즙
- 최근 올라온 답변들 스트리밍 기능 추가
- 새 질문 알림창 누르면 닫히도록
- 웹소켓 스트리밍 인디케이터 작성
=> 최근 올라온 답변들 실시간 스트리밍 (w/ 웹소켓)

config/docker.env.example, config/local_dev_example.env, package-lock.json, package.json, src/app/_components/answer.tsx, src/app/_dto/websocket-event/websocket-event.dto.ts, src/app/api/_service/websocket/websocket-service.ts, src/app/api/_utils/getIp/get-ip-from-Request.ts, src/app/api/_utils/profileToDto.ts, src/app/main/_header.tsx, src/app/main/questions/action.ts, src/utils/logger/Logger.ts, tsconfig.server.json
- Websocket 백앤드/프론트엔드
- Websocket Answer 이벤트에도 프로필 DTO 같이 오도록
- 최대 재연결 시도 카운터 도입
=> Refactor: 웹소켓

package-lock.json, package.json, src/app/api/_service/websocket/websocket-service.ts, src/app/main/_header.tsx
=> Fix: Websocket

src/app/api/_service/websocket/websocket-service.ts
* Fix: Websocket HTTP 쿠키헤더 Regex수정
=> Fix: Websocket HTTP 쿠키헤더 Regex수정

src/app/api/_service/blocking/blocking-service.ts, src/app/api/_service/queue/workers/ImportBlock.ts, src/app/api/user/blocking/create/route.ts
- https://github.com/serafuku/neo-quesdon/issues/98
- Misskey/Mastodon으로부터 Block을 import 해 오는 경우에도 적용
=> ✨ 유저 차단시 이미 받은 질문을 자동거절

src/app/api/_service/question/question-service.ts, src/app/api/db/questions/route.ts, src/app/main/settings/page.tsx
- https://github.com/serafuku/neo-quesdon/issues/99
- 아직 답변하지 않은 질문을 모두 삭제하는 기능을 추가
- 아이고 orderBy를 빼먹었네!!
=> ✨ 모든 미답변 질문을 삭제하는 기능 추가

src/app/api/_service/queue/workers/RefreshFollowService.ts
- 50명 이하인 경우는 link 헤더 자체를 안 주는듯???
=> 🐛 마스토돈 팔로잉 50명 이하일때 수정

src/app/_components/question.tsx, src/app/_dto/fetch-all-answers/fetch-all-answers.dto.ts, src/app/_dto/fetch-user-answers/fetch-user-answers.dto.ts, src/app/api/_service/answer/answer-service.ts, src/app/api/db/answers/[userHandle]/[answerId]/route.ts, src/app/api/db/answers/[userHandle]/route.ts, src/app/api/db/answers/route.ts, src/app/api/db/delete-answer/route.ts, src/app/api/db/fetch-all-answers/route.ts, src/app/api/db/fetch-user-answers/route.ts, src/app/main/layout.tsx, src/app/main/user/[handle]/[answer]/page.tsx, src/app/main/user/[handle]/_answers.tsx
- POST로 통일되어 있던 answer 관련 API들 GET/DELETE/POST 로 변경
- fetch-user-answer 같이 되어있던 endpoint 이름도 `answers/[userHandle]/answerId]` 형식으로 통일
=> 🎨 answer API구조 refactor

.dockerignore, .github/workflows/docker_build.yml, Dockerfile, README.md, docker-compose-example.yml
- `main` 나 `develop` 에 push시, `v**` 태그 푸시, 릴리즈 만들때
- 원래 AMD64, ARM64 Multiarch 이미지를 만들고 싶었는데 생각보다 너무 느려서 취소함. 
- arm64 빌드 더 빠르게 할 방법 생각해 보면 좋을것 같음
=> 👷 Docker github action

src/app/_components/notification.tsx, src/app/globals.css, src/app/main/@modal/(.)notification/page.tsx, src/app/main/@modal/[...catchAll]/page.tsx, src/app/main/@modal/default.tsx, src/app/main/_events.ts, src/app/main/_header.tsx, src/app/main/layout.tsx, src/app/main/notification/page.tsx
- 알림창 Parellel Route와 Intercepting Route로 모달창 & 페이지 구현
- 알림 WebSocket 이벤트핸들러와 Context구현
- :bug: 프로필 컨텍스트 메뉴 클릭해도 안 닫히는 버그 수정
=> :sparkles: 알림창 구현

src/app/main/layout.tsx
- 비 로그인 상태에서 알림 fetch하려다가 오류 메시지 나오는것 수정
=> FIX: 로그인되지 않은 상태에서 알림 fetch하지 않도록

src/app/api/_service/answer/answer-service.ts, src/app/api/_utils/uploadNote/clampText.ts, src/app/api/_utils/uploadNote/mastodonToot.ts, src/app/api/_utils/uploadNote/misskeyNote.ts
- https://github.com/serafuku/neo-quesdon/issues/111
- 겸사겸사 uploadNote 유틸함수들 파일 분리
- 므아...
=> :bug: 글자수 제한 문제 수정

src/app/_components/notification.tsx
=> 💄 프로필 사진에 프로필로 가는 링크 추가

package-lock.json, package.json, src/app/_components/NameComponents.tsx, src/app/_components/answer.tsx, src/app/_components/notification.tsx, src/app/_components/userProfile.tsx, src/app/api/web/proxy/route.ts, src/app/main/_header.tsx, src/app/main/settings/page.tsx, src/app/main/user/[handle]/_profile.tsx, src/utils/getProxyUrl/getProxyUrl.ts
- 직접 <img src= ... 거는 대신 내부 프록시를 통해서 제공하도록
=> :sparkles:  이미지를 프록싱해서 제공하기

src/app/api/web/proxy/route.ts
- 원격 서버에서 준 Content-Type 헤더가 image 가 아닌 경우에 에러 뱉는 대신 application/octet-stream 로 처리하도록
- 사유: 원격 이미지 서버중에 Content-type 헤더가 잘못 설정된 경우가 발견됨 : [예시](https://s3.lapy.link/cc162d4e-6181-4da7-86a5-2e95d4729c14)
=> 🐛 Proxy content-type 처리 수정

src/app/_components/question.tsx
- "메인에서 숨기기":  Toggle 스위치
- Toggle 스위치 변수 이름: hideFromMain
``` js
try {
const req: CreateAnswerDto = {
questionId: questionId,
answer: e.answer,
nsfwedAnswer: e.nsfw,
// TODO: 여기에 hideFromMain 추가
visibility: e.visibility,
};
```
주석처리된 부분에 hideFromMain DTO 추가하기
=> 💄 '메인에서 숨기기' 토글 추가

prisma/migrations/20241221124546_hide_from_main/migration.sql, prisma/migrations/20241221125029_hidefrom_main_idx/migration.sql, prisma/schema.prisma, src/app/_components/question.tsx, src/app/_dto/answers/Answers.dto.ts, src/app/_dto/answers/create-answer.dto.ts, src/app/_dto/websocket-event/websocket-event.dto.ts, src/app/api/_service/answer/answer-service.ts, src/app/api/_service/websocket/websocket-service.ts, src/app/main/_events.ts, src/app/main/layout.tsx
- https://github.com/serafuku/neo-quesdon/issues/122 의 백앤드 구현
- 므아
=> :sparkles: 메인페이지에서 답변 숨기기 기능

src/app/main/user/[handle]/[answer]/page.tsx
=> 🐛 유저 답변에서 로딩 스피너 표시

src/app/main/user/[handle]/page.tsx
=> rel="me" 추가

src/app/_components/question.tsx, src/app/main/_events.ts, src/app/main/layout.tsx, src/app/main/questions/page.tsx, src/app/main/settings/_table.tsx, src/app/main/settings/page.tsx, src/app/main/social/page.tsx, src/app/main/user/[handle]/[answer]/answer.tsx, src/app/main/user/[handle]/[answer]/page.tsx, src/app/main/user/[handle]/_answers.tsx, src/app/main/user/[handle]/_profile.tsx, src/utils/answers/fetchAllAnswers.ts, src/utils/api-error/onApiError.ts, src/utils/block/createBlock.ts, src/utils/questions/deleteQuestion.ts
- API오류시 프론트엔드에서 표시하는 방법을 개선
- onApiError 로 통일 
- onApiErrorEvent 사용
=> :art: API 에러시 에러표시 개선

src/app/_dto/account-delete/account-delete.dto.ts, src/app/api/_service/account/account-delete.service.ts, src/app/api/_service/answer/answer-service.ts, src/app/api/db/answers/[userHandle]/[answerId]/route.ts, src/app/api/user/account-delete/route.ts, src/app/main/settings/page.tsx, src/app/main/user/[handle]/[answer]/not-found.tsx, src/app/main/user/[handle]/[answer]/page.tsx, src/app/main/user/[handle]/_answers.tsx, src/app/main/user/[handle]/not-found.tsx, src/app/main/user/[handle]/page.tsx
- 네오퀘스돈 계정을 삭제하는 기능 추가
- 유저 프로필, 답변의 404페이지 수정
=> :sparkles: 계정 삭제기능 추가 + 버그수정

src/app/main/settings/page.tsx
아이고! JWT를 안 지우니 이후 모든 API에서 에러가 나네!
=> Fix: 계정 삭제 이후 logout 호출 (토큰 삭제)

src/app/_components/answer.tsx, src/app/_components/question.tsx, src/app/_components/userProfile.tsx, src/app/api/_service/account/account-delete.service.ts, src/app/api/_service/queue/queueService.ts, src/app/api/_service/queue/workers/AccountDelete.ts, src/app/api/_service/redis-pubsub/redis-event.service.ts, src/app/api/_service/redisService/redis-service.ts, src/app/api/_utils/getPrismaClient/get-prisma-client.ts, src/app/main/layout.tsx, src/app/main/user/[handle]/page.tsx
- 링크 몇개 prefetch 를 비활성화
- dev모드에서 prisma 클라이언트 연결 계속 늘어나는 문제 해결 
- Redis 클라이언트를 공유해서 쓰도록 수정
- 답변노트 공개범위의 '...' (플레이스홀더 값) 에 disabled 추가 (safari에서 문제 해결)
- 질문함 링크의 미리보기 텍스트에 들어있는 핸들 앞에 `@` 를 붙이도록 변경
- 계정 삭제도 큐 사용하도록
- 답변이 삭제될때 알림 숫자가 마이너스가 될 수 있는 문제 해결
=> 몇가지 자잘한 수정

src/app/api/_service/answer/answer-service.ts, src/app/api/_service/queue/workers/ImportBlock.ts, src/app/api/web/fetch-name-with-emoji/route.ts, src/app/api/web/refresh-token/route.ts, src/app/page.tsx
One caveat: /share endpoint does not exist (yet) on Iceshrimp.NET so it will not work for the foreseeable future.
=> feat/compatibility: Add Iceshrimp.NET support by using its Mastodon API compatibility layer

prisma/migrations/20250221012226_iceshrimp_net/migration.sql, prisma/schema.prisma, src/app/api/_service/answer/answer-service.ts, src/app/api/_service/queue/workers/ImportBlock.ts, src/app/api/_service/queue/workers/RefreshFollowService.ts, src/app/api/web/mastodon-login/route.ts, src/app/api/web/misskey-login/route.ts, src/app/api/web/refresh-token/route.ts
- DB enum에 Iceshrimp.NET 을 추가
- Refresh follow도 동작할 수 있도록 수정
=> Feat: Iceshrimp.NET 지원 추가

prisma/migrations/20250312043932_add_sharkey/migration.sql, prisma/schema.prisma, src/app/api/_service/answer/answer-service.ts, src/app/api/_service/queue/workers/ImportBlock.ts, src/app/api/_service/queue/workers/RefreshFollowService.ts, src/app/api/web/fetch-name-with-emoji/route.ts, src/app/api/web/misskey-login/route.ts, src/app/api/web/refresh-token/route.ts, src/app/page.tsx
- https://github.com/serafuku/neo-quesdon/issues/147
=> :sparkles: Sharkey 지원 추가

src/app/api/web/proxy/route.ts
- URLSearchParams객체는 decode할 필요가 없었구나??
=> 🐛 일부 인스턴스의 이미지 프록시 문제 해결

src/app/api/_service/websocket/websocket-service.ts
- Ping timeout 시 `clearInterval` 추가
=> Websocket timeout 예외처리 추가
